Fix crash on copy() of empty files
Avoid copying empty files in php_copy_file_ctx by creating an empty destination file and returning early.

This change is needed because the `copy()` function can’t handle empty files:

```
// This code:
console.log(await php.run(`<?php
     file_put_contents('empty.txt', '');
     var_dump(copy('empty.txt', 'copied_empty.txt'));
`));

// Triggers this error:
TypeError: Cannot read properties of null (reading 'buffer')
    at Object.mmap (http://127.0.0.1:8778/php-web.js:2764:40)
    at Object.mmap (http://127.0.0.1:8778/php-web.js:3787:34)
    at syscallMmap2 (http://127.0.0.1:8778/php-web.js:5862:22)
    at ___sys_mmap2 (http://127.0.0.1:8778/php-web.js:5870:14)
    at ___syscall192 (http://127.0.0.1:8778/php-web.js:5877:10)
    at ___mmap (wasm://wasm/04421bd2:wasm-function[8927]:0x9473e2)
    at _php_stdiop_set_option (wasm://wasm/04421bd2:wasm-function[2855]:0x3209c9)
    at __php_stream_set_option (wasm://wasm/04421bd2:wasm-function[2747]:0x314b63)
    at __php_stream_mmap_range (wasm://wasm/04421bd2:wasm-function[2879]:0x325b18)
    at __php_stream_copy_to_stream_ex (wasm://wasm/04421bd2:wasm-function[2761]:0x317285)
```

As a consequence, installing WordPress plugins often fails as many plugins ship with at least one empty file.

However, the copy() function works well with files that have content:

```js
console.log(await php.run(`<?php
     file_put_contents('with_content.txt', 'hey!');
     var_dump(copy('with_content.txt', 'with_content.txt'));
     // bool(true);
`));
```

The crash occurs on MEMFS and WASMFS. The root cause is unclear at the moment.